version: '3.8'

services:
  api_events_shatynska_green:
    image: shatynska/api-events-shatynska:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-public'
      - 'traefik.http.routers.api_events_shatynska_green.entrypoints=https'
      - 'traefik.http.routers.api_events_shatynska_green.rule=(Host(`shatynska.com`) && PathPrefix(`/api`))'
      - 'traefik.http.routers.api_events_shatynska_green.tls=true'
      - 'traefik.http.routers.api_events_shatynska_green.tls.certresolver=letsEncrypt'
      - 'traefik.http.services.api_events_shatynska_green.loadbalancer.server.port=3000'
    ports:
      - 3040:3000
    networks:
      - traefik-public
      - events-shatynska

networks:
  traefik-public:
    external: true
  events-shatynska:
    external: true
